<?php if ($this->pageCount>1): ?>


	<ul class="paginationControl">
		<!-- Previous page link -->
		<?php if (isset($this->previous)): ?>
		<li class="numPage">
		  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
		   &lt; </a>
		</li>
		<?php endif; ?>
	
		<!-- Numbered page links -->
		<?php foreach ($this->pagesInRange as $page): ?>
		
		  <?php if ($page != $this->current): ?>
                    <li class="numPage">
		    <a href="<?php echo $this->url(array('page' => $page)); ?>">
		        <?php echo $page; ?></a>
		  <?php else: ?>
                        <li class="numPage <?php echo $this->pageCount>100 ? "numPageSelectedAuto" : "numPageSelectedNormal" ;?>">
		    <?php echo $page; ?>/<?php echo $this->pageCount; ?>
		  <?php endif; ?>
		</li>
		<?php endforeach; ?>
	
		<!-- Next page link -->
		<?php if (isset($this->next)): ?>
		<li class="numPage">
		  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
		    &gt;</a>
		</li>
		<?php endif; ?>
	</ul>
<?php endif; ?>