<?php $this->tabPane("tab",
                  "",
                  array('title' => "Catégories")); ?>

<?php $this->tabPane("tab",
                  "",
                  array('title' => "Films")); ?>

<?php $this->tabPane("tab",
                  "",
                  array('title' => "Tags")); ?>



<?php echo $this->tabContainer("tab",
                        array(),
                        array('class' => 'flora' )); ?>

